language: node_js
node_js:
  - "8"

cache: yarn

install:
  - yarn


script: yarn run test

##Submit Coverage Status to coveralls.io
after_script:
  - cat ./src/test/unit/coverage/lcov.info | ./node_modules/.bin/coveralls
